config/routes.rb
Rails.application.routes.draw do

  get 'pages/index'

  # get '/users/edit' => 'users#edit'
  get '/login' => "session#new"
  post '/login' => "session#create"
  delete '/logout' => "session#destroy"
  get 'store/index' => 'store#index', :as => 'store'

  root :to => 'pages#app'

  get '/app' => 'pages#app', :as => 'app'

  resources :carts
  resources :users
  resources :line_items
  resources :products
  resources :orders
  resources :charges

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "OnlineStore" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body class="<%= params[:controller] %>-<%= params[:action] %>">

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#store">Online Store</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
          <% if @current_user.present? %>
              <li><%= link_to("My Details", root_path+'#mydetails') %></li>
              <% if @current_user.role == 'admin' %>
                <li><%= link_to 'Orders', orders_path %></li>
                <li><%= link_to 'Products', products_path %></li>
                <li><%= link_to 'Users', users_path %></li>
              <% end %>
              <li><%= link_to("Logout #{ @current_user.name }", logout_path, :method => :delete) %></li>
            <% else %>
              <li><%= link_to new_user_path do%>
                  <span class="glyphicon glyphicon-user"> </span> Sign up
                  <% end %>
              </li>
              <li><%= link_to login_path do %>
                <span class="glyphicon glyphicon-log-in"> </span> Login
              <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

  <div id="wrap">
    <div class="container clear-top">
      <div class="col-lg-9">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
      <div class="col-lg-3" id="">
        <ul id="cartLineItemViewContainer">
        </ul>
        <% if @cart && @cart.line_items.present? %>
          <div class="col-lg-3">
            <div class="well sidebar-nav">
                <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
                  <%= render @cart %>
                <% end %>
              </div>
            </div><!--/.well -->
          </div><!--/span-->
        <% end %>
      </div><!--/row-->
    </div>
  </div>
      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>